domains:
  - ai-player.team3.techtitans.be
  - www.ai-player.team3.techtitans.be
  - metabase.team3.techtitans.be
  - www.metabase.team3.techtitans.be
  - ai-chatbot.team3.techtitans.be
  - www.ai-chatbot.team3.techtitans.be
  - recommendation.team3.techtitans.be
  - www.recommendation.team3.techtitans.be
  - rabbitmq.team3.techtitans.be
  - www.rabbitmq.team3.techtitans.be